/* Generated By:JavaCC: Do not edit this line. TuringMachineConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TuringMachineConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int DIRECTION = 6;
  /** RegularExpression Id. */
  int SYMBOL = 7;
  /** RegularExpression Id. */
  int STATE_KEYWORD = 8;
  /** RegularExpression Id. */
  int CARD_BEG_KEYWORD = 9;
  /** RegularExpression Id. */
  int CARD_END_KEYWORD = 10;
  /** RegularExpression Id. */
  int READ_KEYWORD = 11;
  /** RegularExpression Id. */
  int WRITE_KEYWORD = 12;
  /** RegularExpression Id. */
  int MOVE_KEYWORD = 13;
  /** RegularExpression Id. */
  int JUMP_KEYWORD = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<INTEGER>",
    "<DIRECTION>",
    "<SYMBOL>",
    "\"State\"",
    "\"{\"",
    "\"}\"",
    "\"read\"",
    "\"write\"",
    "\"move\"",
    "\"jump\"",
    "\";\"",
    "\",\"",
  };

}
