/* Generated By:JavaCC: Do not edit this line. TuringMachineTreeConstants.java Version 6.0_1 */
public interface TuringMachineTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTTOKENERROR_SKIPTO = 1;
  public int JJTREAD = 2;
  public int JJTWRITE = 3;
  public int JJTSTATE = 4;
  public int JJTNEXTSTATE = 5;
  public int JJTDIRECTION = 6;
  public int JJTLINE = 7;
  public int JJTENDSTATE = 8;
  public int JJTCARD = 9;
  public int JJTFILE = 10;
  public int JJTSTART = 11;


  public String[] jjtNodeName = {
    "error_skipto",
    "tokenerror_skipto",
    "read",
    "write",
    "state",
    "nextstate",
    "direction",
    "line",
    "endstate",
    "card",
    "file",
    "Start",
  };
}
/* JavaCC - OriginalChecksum=fb965e657756133f91f28a6e04956da0 (do not edit this line) */
