/* Generated By:JavaCC: Do not edit this line. TuringMachineTreeConstants.java Version 6.0_1 */
public interface TuringMachineTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTTOKENERROR_SKIPTO = 1;
  public int JJTREAD = 2;
  public int JJTWRITE = 3;
  public int JJTSTATE = 4;
  public int JJTJUMP = 5;
  public int JJTMOVE = 6;
  public int JJTLINE = 7;
  public int JJTVOID = 8;
  public int JJTCARD = 9;
  public int JJTTURINGMACHINE = 10;


  public String[] jjtNodeName = {
    "error_skipto",
    "tokenerror_skipto",
    "READ",
    "WRITE",
    "STATE",
    "JUMP",
    "MOVE",
    "LINE",
    "void",
    "CARD",
    "TURINGMACHINE",
  };
}
/* JavaCC - OriginalChecksum=5d3dc5636751601e8f84a70e4aaa16f9 (do not edit this line) */
