/* Generated By:JavaCC: Do not edit this line. TuringMachineTreeConstants.java Version 6.0_1 */
public interface TuringMachineTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTTOKENERROR_SKIPTO = 1;
  public int JJTREAD = 2;
  public int JJTWRITE = 3;
  public int JJTSTATE = 4;
  public int JJTJUMP = 5;
  public int JJTEND = 6;
  public int JJTMOVE = 7;
  public int JJTLINE = 8;
  public int JJTVOID = 9;
  public int JJTCARD = 10;
  public int JJTTURINGMACHINE = 11;


  public String[] jjtNodeName = {
    "error_skipto",
    "tokenerror_skipto",
    "READ",
    "WRITE",
    "STATE",
    "JUMP",
    "END",
    "MOVE",
    "LINE",
    "void",
    "CARD",
    "TURINGMACHINE",
  };
}
/* JavaCC - OriginalChecksum=343ca3eccb842b8007fcf12ac1c9494a (do not edit this line) */
