/* Generated By:JavaCC: Do not edit this line. TuringMachineConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TuringMachineConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVERYTHINGELSE = 9;
  /** RegularExpression Id. */
  int INTEGER = 10;
  /** RegularExpression Id. */
  int DIRECTION = 11;
  /** RegularExpression Id. */
  int SYMBOL = 12;
  /** RegularExpression Id. */
  int STATE_KEYWORD = 13;
  /** RegularExpression Id. */
  int CARD_BEG_KEYWORD = 14;
  /** RegularExpression Id. */
  int CARD_END_KEYWORD = 15;
  /** RegularExpression Id. */
  int READ_KEYWORD = 16;
  /** RegularExpression Id. */
  int WRITE_KEYWORD = 17;
  /** RegularExpression Id. */
  int MOVE_KEYWORD = 18;
  /** RegularExpression Id. */
  int JUMP_KEYWORD = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int NOTANUMBER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<EVERYTHINGELSE>",
    "<INTEGER>",
    "<DIRECTION>",
    "<SYMBOL>",
    "\"State\"",
    "\"{\"",
    "\"}\"",
    "\"read\"",
    "\"write\"",
    "\"move\"",
    "\"jump\"",
    "\";\"",
    "\",\"",
    "<NOTANUMBER>",
  };

}
